package technology.rocketjump.saul.input;

public enum CommandName {
	PAN_CAMERA_UP,
	PAN_CAMERA_DOWN,
	PAN_CAMERA_LEFT,
	PAN_CAMERA_RIGHT,
	FAST_PAN,
	ZOOM_IN,
	ZOOM_OUT,
	ROTATE,
	PAUSE,
	GAME_SPEED_NORMAL,
	GAME_SPEED_FAST,
	GAME_SPEED_FASTER,
	GAME_SPEED_FASTEST,
	QUICKSAVE,
	QUICKLOAD,

	//debug options
	DEBUG_FRAME_BUFFER_0,
	DEBUG_FRAME_BUFFER_1,
	DEBUG_FRAME_BUFFER_2,
	DEBUG_FRAME_BUFFER_3,
	DEBUG_FRAME_BUFFER_4,
	DEBUG_FRAME_BUFFER_5,
	DEBUG_FRAME_BUFFER_6,
	DEBUG_FRAME_BUFFER_7,
	DEBUG_FRAME_BUFFER_8,
	DEBUG_FRAME_BUFFER_9,
	DEBUG_SHOW_JOB_STATUS,
	DEBUG_TOGGLE_FLOOR_OVERLAP_RENDERING,
	DEBUG_SHOW_INDIVIDUAL_LIGHTING_BUFFERS,
	DEBUG_SHOW_LIQUID_FLOW,
	DEBUG_SHOW_ZONES,
	DEBUG_SHOW_PATHFINDING_NODES,
	DEBUG_HIDE_GUI,
	DEBUG_GAME_SPEED_ULTRA_FAST,
	DEBUG_GAME_SPEED_SLOW,
	DEBUG_SHOW_MENU
	;

	//TODO: translations

	public static CommandName parse(String value) {
		for (CommandName commandName : values()) {
			if (commandName.name().equals(value)) {
				return commandName;
			}
		}
		return null;
	}
}
