package technology.rocketjump.saul.ui.views.debug;

public enum DebugAction {

	NONE,
	SPAWN_CREATURE,
	SPAWN_ITEM,
	SPAWN_PLANT,
	SPAWN_SETTLER,
	DESTROY_ENTITY,
	CHANGE_CREATURE_NEED,
	KILL_CREATURE,
	TRIGGER_FIRE,
	TRIGGER_LIGHTNING,
	TRIGGER_IMMIGRATION,
	TRIGGER_NEXT_WEATHER,
	TRIGGER_YEAR_END,
	TOGGLE_PIPE,
	TOGGLE_CHANNEL,
	TRIGGER_BREAKDOWN,
	UNCOVER_UNEXPLORED_AREA,
	TRIGGER_TEST_EFFECT,
	PRETEND_ATTACKED_BY_NEARBY_CREATURE,
	TRIGGER_INVASION,
    DESTROY_BODY_PART

}
